### ISSUE TITLE
Setting already uploaded files from S3 to Dropzone Wrapper

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [zefoy/ngx-dropzone-wrapper#119] opened 2018-10-29 06:45 UTC
Hello,

I am trying to retrieve the file content from AWS S3 which comes as a U8IntArray. I want to bind this uploaded file to the list of added files in the Dropzone wrapper. I have created a dropzone directive 

`@ViewChild(DropzoneDirective) directiveRef?: DropzoneDirective;`

I have tried to call the add event and complete event but it doesnt show it too.
`
const mockFile = { name: 'logo.jpg', size: 76478};
this.directiveRef.DZ_ADDEDFILE.emit(mockFile);
this.directiveRef.DZ_THUMBNAIL.emit(this.settings.companyDetails.logoFilePath);
this.directiveRef.DZ_COMPLETE.emit(mockFile);
`

I am not able to bind the file. I am using this in `ngAfterViewInit` so the dropzone is also available to work with.

Please let me know how its done for file obtained from AWS S3 and show it in the dropzone.

Thanks a lot

**Comment by sconix** [comment] 2018-11-23 14:30
Duplicate of #99

**Closed by sconix** 2018-11-23 14:30 UTC
Labels: question
